# Generated by Django 2.2.2 on 2019-06-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_series_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='series',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='series',
            name='vote_score',
        ),
    ]
