# Generated by Django 2.2.2 on 2019-06-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pk', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_type', models.CharField(choices=[('series', 'Series'), ('tutorial', 'Tutorial')], max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author')),
            ],
        ),
    ]
